name: Build LazyPM
on:
    pull_request:
        branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
          
        - name: Install build dependencies
          run: |
              sudo apt-get update
              sudo apt-get install -y gcc build-essential
              
        - name: Build nob
          run: gcc ./build/nob.c -o ./build/nob
          
        - name: Build project
          run: ./build/nob
