name: LazyPM Check Code Format

on:
    pull_request:
        branches: [ main ]

jobs:
    format-check:
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
          
        - name: Install clang-format
          run: |
              sudo apt-get update
              sudo apt-get install -y clang-format
              
        - name: Check code formatting
          run: |
              # Find all C source files and check formatting (excluding build/nob.h and src/external)
              format_failed=false
              while read file; do
                  if ! clang-format --dry-run --Werror "$file" > /dev/null 2>&1; then
                      echo "❌ $file"
                      format_failed=true
                  else
                      echo "✅ $file"
                  fi
              done < <(find . -name "*.c" -o -name "*.h" | grep -v "./build/nob.h" | grep -v "./src/external/")
              
              if [ "$format_failed" = true ]; then
                  exit 1
              fi
              
              echo "✅ All files are properly formatted!"
